export const STUDY_ERROR_CODES = [
  "FEATURE_DISABLED",
  "INVALID_STATE_TRANSITION",
  "IDEMPOTENCY_CONFLICT",
  "OWNERSHIP_MISMATCH",
  "UNSUPPORTED_EVENT",
  "INVALID_EVIDENCE",
  "INTEGRITY_REJECTED",
] as const;

export type StudyErrorCode = (typeof STUDY_ERROR_CODES)[number];