export type GamificationErrorCode =
  | "GAMIFICATION_DEFINITION_INVALID"
  | "GAMIFICATION_DEFINITION_BUNDLE_NOT_FOUND"
  | "GAMIFICATION_DEFINITION_CHECKSUM_MISMATCH"
  | "GAMIFICATION_RULE_VERSION_NOT_FOUND"
  | "GAMIFICATION_RULE_VERSION_CONFLICT"
  | "GAMIFICATION_RULE_SET_NOT_DRAFT"
  | "GAMIFICATION_RETIRED_RULE_SET_CANNOT_REACTIVATE"
  | "GAMIFICATION_ACTIVE_RULE_SET_NOT_CONFIGURED"
  | "GAMIFICATION_ACTIVE_RULE_SET_INVARIANT_FAILED"
  | "GAMIFICATION_METRIC_NOT_FOUND"
  | "GAMIFICATION_METRIC_PROVIDER_UNAVAILABLE"
  | "GAMIFICATION_METRIC_VALUE_INVALID"
  | "GAMIFICATION_USER_NOT_FOUND"
  | "GAMIFICATION_ACHIEVEMENT_RECORD_INVALID"
  | "GAMIFICATION_ACHIEVEMENT_PROGRESS_INVALID"
  | "GAMIFICATION_ACHIEVEMENT_PROGRESS_MISSING"
  | "GAMIFICATION_LEVEL_POINTS_INVALID"
  | "GAMIFICATION_LEVEL_DEFINITIONS_INVALID"
  | "GAMIFICATION_LEVEL_DEFINITION_CHECKSUM_MISMATCH"
  | "GAMIFICATION_LEVEL_STATE_INVALID"
  | "GAMIFICATION_CHALLENGE_DEFINITION_CHECKSUM_MISMATCH"
  | "GAMIFICATION_CHALLENGE_DEFINITION_VERSION_NOT_FOUND"
  | "GAMIFICATION_CHALLENGE_INSTANCE_INVALID"
  | "GAMIFICATION_CHALLENGE_PROGRESS_INVALID"
  | "GAMIFICATION_CHALLENGE_PROGRESS_MISSING"
  | "GAMIFICATION_CHALLENGE_RECONCILIATION_INVALID"
  | "GAMIFICATION_INVALID_INPUT";

export class GamificationError extends Error {
  constructor(
    public readonly code: GamificationErrorCode,
    message: string = code,
  ) {
    super(message);
    this.name = "GamificationError";
  }
}