import React, { memo } from "react";
import { useReliableLegalScroll } from "../useReliableLegalScroll";
import { ChevronLeft, ChevronRight, LifeBuoy } from "lucide-react";
import type { Language } from "../../../core/i18n/translations";
interface SupportViewProps { onBack: () => void; language?: Language; }
const SupportView = ({ onBack, language = "en" }: SupportViewProps) => {
  const scrollRef=useReliableLegalScroll(); const ar=language==="ar"; const BackIcon=ar?ChevronRight:ChevronLeft;
  return <div ref={scrollRef} dir={ar?"rtl":"ltr"} className="legal-page-scroll h-full w-full bg-[#F8F9FC] dark:bg-[#000000] overflow-y-auto" style={{WebkitOverflowScrolling:"touch",overscrollBehaviorY:"contain",touchAction:"pan-y"}}>
    <div className="legal-page-header sticky top-0 z-40 bg-white/90 dark:bg-[#1C1C1E]/92 backdrop-blur-md border-b border-black/5 dark:border-white/[0.12] px-4 py-3 flex items-center shadow-sm"><button onClick={onBack} aria-label={ar?"رجوع":"Back"} className={`${ar?"-mr-2":"-ml-2"} p-2 rounded-full hover:bg-neutral-100 dark:hover:bg-white/10 text-neutral-600 dark:text-neutral-300`}><BackIcon className="w-6 h-6"/></button><h1 className={`${ar?"mr-2":"ml-2"} text-lg font-semibold text-neutral-900 dark:text-white flex items-center gap-2`}><LifeBuoy className="w-5 h-5 text-indigo-500"/>{ar?"مركز الدعم والمساعدة":"Support & Help Center"}</h1></div>
    <div className="legal-page-content max-w-2xl mx-auto px-4 py-6 text-neutral-800 dark:text-neutral-200"><section className="bg-white dark:bg-[#1C1C1E] p-6 rounded-xl border border-neutral-200/50 dark:border-white/10 shadow-sm space-y-4 text-sm leading-relaxed">
      <p className="text-xs text-neutral-500 dark:text-neutral-400 font-medium">{ar?"آخر تحديث: أغسطس 2026":"Last Updated: August 2026"}</p>
      <h2 className="text-xl font-bold text-neutral-900 dark:text-white pt-2">{ar?"التواصل مع الدعم":"Contact Support"}</h2><p>{ar?"إذا احتجت إلى مساعدة، راسل فريق الدعم على":"If you need help, please email our support team at"} <a href="mailto:99sguide.support@gmail.com" className="text-indigo-500 hover:underline" dir="ltr">99sguide.support@gmail.com</a>.</p>
      <h2 className="text-xl font-bold text-neutral-900 dark:text-white pt-2">{ar?"الأسئلة الشائعة":"Frequently Asked Questions"}</h2><ul className={`${ar?"list-disc pr-5":"list-disc pl-5"} space-y-2`}><li><strong>{ar?"كيف أعيد تعيين كلمة المرور؟":"How do I reset my password?"}</strong> {ar?"يمكنك طلب رابط إعادة التعيين من شاشة تسجيل الدخول.":"You can request a password reset from the login screen."}</li><li><strong>{ar?"هل يُحفظ تقدمي دون اتصال؟":"Is my progress saved offline?"}</strong> {ar?"تتم مزامنة التقدم تلقائيًا عند عودة الاتصال بالإنترنت.":"Progress syncs automatically when you regain internet connectivity."}</li><li><strong>{ar?"هل يمكنني تغيير مجموعتي؟":"Can I change my academic group?"}</strong> {ar?"نعم، يمكنك تحديث معلوماتك من صفحة الملف الشخصي.":"Yes, you can update your profile information in the Profile tab."}</li></ul>
      <h2 className="text-xl font-bold text-neutral-900 dark:text-white pt-2">{ar?"مساعدة الحساب وحذفه":"Account Assistance & Deletion"}</h2><p>{ar?"يمكنك حذف حسابك مباشرة من صفحة الإعدادات. يؤدي الحذف إلى إزالة بياناتك الأكاديمية ومعلوماتك الشخصية نهائيًا وفق آلية الحذف الموضحة داخل التطبيق.":"Account deletion is available directly from the Settings page and permanently removes your academic data and personal information."}</p>
      <h2 className="text-xl font-bold text-neutral-900 dark:text-white pt-2">{ar?"الإبلاغ عن الأخطاء":"How to Report Bugs"}</h2><p>{ar?"إذا واجهت مشكلة تقنية، أرسل لنا نوع جهازك وإصدار النظام ووصفًا واضحًا للمشكلة. إرفاق صورة أو تسجيل شاشة يساعدنا على تشخيصها بسرعة.":"If you encounter a technical issue, email us your device model, operating system, and a clear description of the problem. Screenshots or screen recordings are very helpful."}</p>
      <h2 className="text-xl font-bold text-neutral-900 dark:text-white pt-2">{ar?"وقت الاستجابة":"Response Time"}</h2><p>{ar?"نسعى للرد على استفسارات الدعم خلال 48–72 ساعة عمل.":"Our technical support team aims to respond to inquiries within 48–72 business hours."}</p>
    </section></div>
  </div>;
};
export default memo(SupportView);
