export const LEADERBOARD_ERROR_CODES = [
  "LEADERBOARD_INVALID_INPUT",
  "LEADERBOARD_SEASON_NOT_FOUND",
  "LEADERBOARD_SEASON_CONFIGURATION_MISSING",
  "LEADERBOARD_SEASON_CONFIGURATION_CONFLICT",
  "LEADERBOARD_SEASON_NOT_FINALIZABLE",
  "LEADERBOARD_SNAPSHOT_NOT_FOUND",
  "LEADERBOARD_SNAPSHOT_INCONSISTENT",
  "LEADERBOARD_CURSOR_INVALID",
  "LEADERBOARD_CURSOR_EXPIRED",
  "LEADERBOARD_POINTS_COMPATIBILITY_CONFLICT",
  "LEADERBOARD_POINTS_LEDGER_ONLY_NOT_READY",
  "LEADERBOARD_AGGREGATE_OVERFLOW",
] as const;

export type LeaderboardErrorCode = typeof LEADERBOARD_ERROR_CODES[number];

export class LeaderboardError extends Error {
  constructor(
    readonly code: LeaderboardErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "LeaderboardError";
  }
}